"""empty message

Revision ID: 6e332df593f6
Revises: c20b236149de
Create Date: 2020-06-16 16:07:38.573707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e332df593f6'
down_revision = 'c20b236149de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=True),
    sa.Column('screen_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hashtags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tweets', sa.Column('twitter_id', sa.Integer(), nullable=True))
    op.drop_column('tweets', 'tweet_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('tweet_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tweets', 'twitter_id')
    op.drop_table('hashtags')
    op.drop_table('atuser')
    # ### end Alembic commands ###
